import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useNavigate, Link } from 'react-router-dom';
import { useAuthStore } from '@/stores/authStore';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { api } from '@/lib/axios';
import boxLogo from '@/assets/box-logo.jpg';


const registerSchema = z.object({
    username: z.string().min(3, { message: "Username must be at least 3 characters" }),
    email: z.string().email({ message: "Invalid email address" }),
    password: z.string().min(6, { message: "Password must be at least 6 characters" }),
    confirmPassword: z.string(),
}).refine((data) => data.password === data.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"],
});

type RegisterFormValues = z.infer<typeof registerSchema>;

export default function RegisterPage() {
    const [error, setError] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const navigate = useNavigate();
    const login = useAuthStore((state) => state.login);

    const { register, handleSubmit, formState: { errors } } = useForm<RegisterFormValues>({
        resolver: zodResolver(registerSchema),
    });

    const onSubmit = async (data: RegisterFormValues) => {
        setIsLoading(true);
        setError(null);
        try {
            const response = await api.post('/auth/local/register', {
                username: data.username,
                email: data.email,
                password: data.password,
                // role_custom: "SALES", // FIXME: This field causes 400 Bad Request on standard Strapi. Requires backend customization.
            });

            const { user, jwt } = response.data;
            login(user, jwt);

            // Auto-create Sales Profile
            try {
                // UID is now generated by Backend (Lifecycle Hook)
                await api.post('/sales-profiles', {
                    data: {
                        sales_uid: `SALES-${Date.now()}`, // Temporary UID to satisfy required field
                        email: user.email,
                        surename: user.username.toUpperCase(),
                        approved: false,
                        blocked: false
                    }
                });
            } catch (profileError) {
                console.error("Failed to create sales profile:", profileError);
                // Proceed anyway, profile can be created later or handled by admin
            }

            navigate('/profile');
        } catch (err: any) {
            console.error("Registration Error Details:", err.response?.data || err);
            setError(err.response?.data?.error?.message || 'Registration failed');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <Card className="w-full shadow-lg border-t-4 border-t-primary">
            <CardHeader className="flex flex-col items-center space-y-2">
                <img src={boxLogo} alt="Logo" className="h-16 w-auto mb-2" />
                <CardTitle className="text-2xl font-bold text-primary">Join Sales App</CardTitle>
                <CardDescription>Create a new account for Sales Access.</CardDescription>
            </CardHeader>
            <form onSubmit={handleSubmit(onSubmit)}>
                <CardContent className="space-y-4">
                    <div className="space-y-2">
                        <Label htmlFor="username">Username</Label>
                        <Input id="username" type="text" placeholder="johndoe" {...register('username')} />
                        {errors.username && <p className="text-sm text-red-500">{errors.username.message}</p>}
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="email">Email</Label>
                        <Input id="email" type="email" placeholder="sales@dealer.com" {...register('email')} />
                        {errors.email && <p className="text-sm text-red-500">{errors.email.message}</p>}
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="password">Password</Label>
                        <Input id="password" type="password" {...register('password')} />
                        {errors.password && <p className="text-sm text-red-500">{errors.password.message}</p>}
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="confirmPassword">Confirm Password</Label>
                        <Input id="confirmPassword" type="password" {...register('confirmPassword')} />
                        {errors.confirmPassword && <p className="text-sm text-red-500">{errors.confirmPassword.message}</p>}
                    </div>
                    {error && <p className="text-sm text-red-500">{error}</p>}
                </CardContent>
                <CardFooter className="flex flex-col space-y-2">
                    <Button type="submit" className="w-full bg-primary hover:bg-primary/90" disabled={isLoading}>
                        {isLoading ? 'Creating Account...' : 'Register'}
                    </Button>
                    <div className="text-sm text-center text-gray-500">
                        Already have an account? <Link to="/auth/login" className="text-primary hover:underline font-semibold">Login</Link>
                    </div>
                </CardFooter>
            </form>
        </Card>
    );
}
